CREATE TABLE CSM_SKCHK_MJR_CLASS (
    MJR_CLASS_CD        VARCHAR2(10) NOT NULL,
    MJR_CLASS_NM        VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CSM_SKCHK_MJR_CLASS PRIMARY KEY (MJR_CLASS_CD)
);

COMMENT ON TABLE PK_CSM_SKCHK_MJR_CLASS IS 'スキルチェック大分類テーブル';

COMMENT ON COLUMN PK_CSM_SKCHK_MJR_CLASS.MJR_CLASS_CD IS '大分類コード';

COMMENT ON COLUMN PK_CSM_SKCHK_MJR_CLASS.MJR_CLASS_NM IS '大分類名称';


CREATE TABLE CSM_SKCHK_MED_CLASS (
    MED_CLASS_CD        VARCHAR2(10) NOT NULL,
    MED_CLASS_NM        VARCHAR2(100) NOT NULL,
    MJR_CLASS_CD        VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CSM_SKCHK_MED_CLASS PRIMARY KEY (MED_CLASS_CD) 
);


