-- 変換対象のテーブルとカラム名を管理するテーブル
DROP TABLE CONV_TARGET_COLUMN_TBL CASCADE CONSTRAINTS PURGE;

CREATE TABLE CONV_TARGET_COLUMN_TBL
(
    TABLE_NAME      VARCHAR2(128) NOT NULL,
    COLUMN_NAME     VARCHAR2(128) NOT NULL,
    CONV_FLG        CHAR(1) NOT NULL,
    CONSTRAINT PK_CONV_TARGET_COLUMN_TBL PRIMARY KEY(TABLE_NAME, COLUMN_NAME)
) TABLESPACE CAREER;

