-- ‘Å‘Ö‚¦‘ÎÛŽÐˆõî•ñ‚ðŠÇ—‚·‚éƒe[ƒuƒ‹
DROP TABLE CONV_PERSONAL_TBL CASCADE CONSTRAINTS PURGE;

CREATE TABLE CONV_PERSONAL_TBL
(
    OLD_SIMEI_NO        VARCHAR2(10) NOT NULL,
    NEW_SIMEI_NO        VARCHAR2(10) NOT NULL
) TABLESPACE CAREER;

