-- 変換テーブル
-- 顧客受領のExcel資料から作成するテーブル
DROP TABLE CONV_RULE_TBL CASCADE CONSTRAINTS PURGE;

CREATE TABLE CONV_RULE_TBL
(
    SHOZOKU_CD      VARCHAR2(10) NOT NULL,
    OLD_SIMEI_NO    VARCHAR2(10) NOT NULL,
    NEW_SIMEI_NO    VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CONV_RULE_TBL PRIMARY KEY(SHOZOKU_CD, OLD_SIMEI_NO)
) TABLESPACE CAREER;

