-- ワークテーブル＆パッケージの削除
DROP TABLE CONV_PERSONAL_TBL CASCADE CONSTRAINTS PURGE;
DROP TABLE CONV_RULE_TBL CASCADE CONSTRAINTS PURGE;
DROP TABLE CONV_TARGET_COLUMN_TBL CASCADE CONSTRAINTS PURGE;

DROP PACKAGE PLPKG_CONVERT_SIMEI_NO;

exit
