prompt 表領域「CAREER」の作成中...
CREATE TABLESPACE CAREER
DATAFILE 'D:\app\Administrator\oradata\CAREER\CAREER.DBF' SIZE 5000M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
BLOCKSIZE 8K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
prompt 表領域「CAREER_D」の作成中...
CREATE TABLESPACE CAREER_D
DATAFILE 'D:\app\Administrator\oradata\CAREER\CAREER_D.DBF' SIZE 5000M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
BLOCKSIZE 8K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
prompt 表領域「CAREER_I」の作成中...
CREATE TABLESPACE CAREER_I
DATAFILE 'D:\app\Administrator\oradata\CAREER\CAREER_I.DBF' SIZE 5000M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
BLOCKSIZE 8K
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
/
prompt 一時表領域「TEMPORARY」の作成...
CREATE TEMPORARY TABLESPACE TEMPORARY
TEMPFILE 'D:\app\Administrator\oradata\CAREER\TEMPORARY.DBF' SIZE 1000M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
/

exit
