insert into MS_LOCATION values('0','札幌', current_timestamp, null, null);
insert into MS_LOCATION values('1','函館', current_timestamp, null, null);
insert into MS_LOCATION values('2','福島', current_timestamp, null, null);
insert into MS_LOCATION values('3','新潟', current_timestamp, null, null);
insert into MS_LOCATION values('4','東京', current_timestamp, null, null);
insert into MS_LOCATION values('5','中山', current_timestamp, null, null);
insert into MS_LOCATION values('6','中京', current_timestamp, null, null);
insert into MS_LOCATION values('7','京都', current_timestamp, null, null);
insert into MS_LOCATION values('8','阪神', current_timestamp, null, null);
insert into MS_LOCATION values('9','小倉', current_timestamp, null, null);

insert into MS_RANK values('0','オープン', current_timestamp, null, null);
insert into MS_RANK values('1','新馬', current_timestamp, null, null);
insert into MS_RANK values('2','未勝利', current_timestamp, null, null);
insert into MS_RANK values('3','500万以下', current_timestamp, null, null);
insert into MS_RANK values('4','1000万以下', current_timestamp, null, null);
insert into MS_RANK values('5','1500万以下', current_timestamp, null, null);
insert into MS_RANK values('6','1600万以下', current_timestamp, null, null);

insert into MS_DISTANCE values('100','1000m', current_timestamp, null, null);
insert into MS_DISTANCE values('101','1100m', current_timestamp, null, null);
insert into MS_DISTANCE values('102','1200m', current_timestamp, null, null);
insert into MS_DISTANCE values('103','1300m', current_timestamp, null, null);
insert into MS_DISTANCE values('200','1400m', current_timestamp, null, null);
insert into MS_DISTANCE values('201','1500m', current_timestamp, null, null);
insert into MS_DISTANCE values('202','1600m', current_timestamp, null, null);
insert into MS_DISTANCE values('203','1700m', current_timestamp, null, null);
insert into MS_DISTANCE values('204','1800m', current_timestamp, null, null);
insert into MS_DISTANCE values('205','1900m', current_timestamp, null, null);
insert into MS_DISTANCE values('300','2000m', current_timestamp, null, null);
insert into MS_DISTANCE values('301','2100m', current_timestamp, null, null);
insert into MS_DISTANCE values('302','2200m', current_timestamp, null, null);
insert into MS_DISTANCE values('303','2300m', current_timestamp, null, null);
insert into MS_DISTANCE values('304','2400m', current_timestamp, null, null);
insert into MS_DISTANCE values('305','2500m', current_timestamp, null, null);
insert into MS_DISTANCE values('400','2600m', current_timestamp, null, null);
insert into MS_DISTANCE values('401','2700m', current_timestamp, null, null);
insert into MS_DISTANCE values('402','2800m', current_timestamp, null, null);
insert into MS_DISTANCE values('403','2900m', current_timestamp, null, null);
insert into MS_DISTANCE values('404','3000m', current_timestamp, null, null);
insert into MS_DISTANCE values('500','3100m', current_timestamp, null, null);
insert into MS_DISTANCE values('501','3200m', current_timestamp, null, null);
insert into MS_DISTANCE values('502','3300m', current_timestamp, null, null);
insert into MS_DISTANCE values('503','3400m', current_timestamp, null, null);
insert into MS_DISTANCE values('504','3500m', current_timestamp, null, null);
insert into MS_DISTANCE values('505','3600m', current_timestamp, null, null);
insert into MS_DISTANCE values('506','3700m', current_timestamp, null, null);
insert into MS_DISTANCE values('507','3800m', current_timestamp, null, null);
insert into MS_DISTANCE values('508','3900m', current_timestamp, null, null);
insert into MS_DISTANCE values('509','4000m', current_timestamp, null, null);
insert into MS_DISTANCE values('510','4100m', current_timestamp, null, null);
insert into MS_DISTANCE values('511','4200m', current_timestamp, null, null);

insert into MS_COURSE values('0', '芝', current_timestamp, null, null);
insert into MS_COURSE values('1', 'ダート', current_timestamp, null, null);
insert into MS_COURSE values('2', '障害', current_timestamp, null, null);
