SPOOL DEL_INS_T31_SYOKUI_TBL.log

DELETE T31_SYOKUI_TBL
/

INSERT INTO T31_SYOKUI_TBL
(
SYOKUI_CODE,
SYOKUI
)
SELECT POST_CODE
      ,POST_NAME
  FROM SHUGYO.DPTPOST DPT
 WHERE BASE_ID = 'Group_common'
   AND (   POST_ID='Post_8'
        OR POST_ID='Post_9'
        OR POST_ID='Post_10'
        OR POST_ID='Post_11'
        OR POST_ID='Post_12'
        OR POST_ID='Post_13'
        OR POST_ID='Post_36'
-- ADD 2015/03/19 バンド変更対応 R.Minamitani start
        OR POST_CODE='270'
        OR POST_CODE='274'
        OR POST_CODE='278'
        OR POST_CODE='282'
        OR POST_CODE='286'
        OR POST_CODE='290'
        OR POST_CODE='294'
        OR POST_CODE='298'
-- ADD 2015/03/19 バンド変更対応 R.Minamitani end
        )
   AND POST_NAME IS NOT NULL
 ORDER BY POST_CODE
/

UPDATE T31_SYOKUI_TBL
	SET SYOKUI_CODE = '215'
	WHERE SYOKUI_CODE = '225'
/

-- ADD 2015/03/19 バンド変更対応 R.Minamitani start
UPDATE T31_SYOKUI_TBL SET SYOKUI_CODE = '170' WHERE SYOKUI_CODE = '270'
/
UPDATE T31_SYOKUI_TBL SET SYOKUI_CODE = '174' WHERE SYOKUI_CODE = '274'
/
UPDATE T31_SYOKUI_TBL SET SYOKUI_CODE = '178' WHERE SYOKUI_CODE = '278'
/
UPDATE T31_SYOKUI_TBL SET SYOKUI_CODE = '182' WHERE SYOKUI_CODE = '282'
/
UPDATE T31_SYOKUI_TBL SET SYOKUI_CODE = '186' WHERE SYOKUI_CODE = '286'
/
UPDATE T31_SYOKUI_TBL SET SYOKUI_CODE = '190' WHERE SYOKUI_CODE = '290'
/
UPDATE T31_SYOKUI_TBL SET SYOKUI_CODE = '194' WHERE SYOKUI_CODE = '294'
/
UPDATE T31_SYOKUI_TBL SET SYOKUI_CODE = '198' WHERE SYOKUI_CODE = '298'
/
-- ADD 2015/03/19 バンド変更対応 R.Minamitani end

COMMIT
/

SPOOL OFF

EXIT
