SPOOL UPDATE_T01_SYOKUI.log

UPDATE T01_PERSONAL_TBL
SET SYOKUI_CODE = (
SELECT DPT.POST_CODE
  FROM SHUGYO.PERSON PER,
       SHUGYO.PARTY_RELATION REL,
       SHUGYO.DPTPOST DPT
 WHERE T01_PERSONAL_TBL.HONMU_FLG = '1'
   AND T01_PERSONAL_TBL.GENSYOKU_TAISYOKU_FLG = '1'
   AND TRIM(T01_PERSONAL_TBL.SIMEI_NO) = TRIM(PER.PERSON_CODE)
   AND PER.PERSON_ID = REL.PARTY_ID
   AND REL.PARTY_RELATION_TYPE = 'PartyRelationPersonPost'
   AND REL.PERIOD_START <= TO_CHAR(SYSDATE, 'YYYY/MM/DD')
   AND REL.PERIOD_END >= TO_CHAR(SYSDATE, 'YYYY/MM/DD')
   AND REL.MASTER_ID = DPT.POST_ID
   AND DPT.BASE_ID = 'Group_common'
   AND (   DPT.POST_ID='Post_8'
        OR DPT.POST_ID='Post_9'
        OR DPT.POST_ID='Post_10'
        OR DPT.POST_ID='Post_11'
        OR DPT.POST_ID='Post_12'
        OR DPT.POST_ID='Post_13'
        OR DPT.POST_ID='Post_36'
-- ADD 2015/03/19 バンド変更対応 R.Minamitani start
        OR DPT.POST_CODE='270'
        OR DPT.POST_CODE='274'
        OR DPT.POST_CODE='278'
        OR DPT.POST_CODE='282'
        OR DPT.POST_CODE='286'
        OR DPT.POST_CODE='290'
        OR DPT.POST_CODE='294'
        OR DPT.POST_CODE='298'
-- ADD 2015/03/19 バンド変更対応 R.Minamitani end
        )
)
/

UPDATE T01_PERSONAL_TBL
SET SYOKUI_CODE = '215'
WHERE SYOKUI_CODE = '225'
/

-- ADD 2015/03/19 バンド変更対応 R.Minamitani start
UPDATE T01_PERSONAL_TBL SET SYOKUI_CODE = '170' WHERE SYOKUI_CODE = '270'
/
UPDATE T01_PERSONAL_TBL SET SYOKUI_CODE = '174' WHERE SYOKUI_CODE = '274'
/
UPDATE T01_PERSONAL_TBL SET SYOKUI_CODE = '178' WHERE SYOKUI_CODE = '278'
/
UPDATE T01_PERSONAL_TBL SET SYOKUI_CODE = '182' WHERE SYOKUI_CODE = '282'
/
UPDATE T01_PERSONAL_TBL SET SYOKUI_CODE = '186' WHERE SYOKUI_CODE = '286'
/
UPDATE T01_PERSONAL_TBL SET SYOKUI_CODE = '190' WHERE SYOKUI_CODE = '290'
/
UPDATE T01_PERSONAL_TBL SET SYOKUI_CODE = '194' WHERE SYOKUI_CODE = '294'
/
UPDATE T01_PERSONAL_TBL SET SYOKUI_CODE = '198' WHERE SYOKUI_CODE = '298'
/
-- ADD 2015/03/19 バンド変更対応 R.Minamitani end

COMMIT
/

SPOOL OFF

EXIT