package jp.co.hisas.career.app.batch.jinik.excelupload.util.property;

public class JinikUploadProperty {
	
	/**
	 * Excel上での項目列位置と回答IDの2次元配列
	 */
	public static final String fillMap[][] = {
			{ "1", "STATUS_NM" },
			{ "3", "OWN_GUID" },
			{ "4", "OWN_PERSON_NAME" },
			{ "5", "DEPT_FULL_NAME" },
			{ "31", "jinik_kaito_ido_month" },
			{ "32", "jinik_kaito_ido_place" },
			{ "33", "jinik_kaito_buyer_jiki" },
			{ "34", "jinik_kaito_buyer_ninteikyu" },
			{ "35", "jinik_kaito_touyo_jiki" },
			{ "36", "jinik_kaito_touyo_keikaku" },
			{ "37", "jinik_kaito_genzai_tanto_gyomu" },
			{ "38", "jinik_kaito_ido_01" },
			{ "39", "jinik_kaito_taishoku_01" },
			{ "40", "jinik_kaito_tanto_gyomu_01" },
			{ "41", "jinik_kaito_ido_month_01" },
			{ "42", "jinik_kaito_shokumu_01" },
			{ "43", "jinik_kaito_jigyojo_01" },
			{ "44", "jinik_kaito_kyoten_01" },
			{ "45", "jinik_kaito_idosaki_kyoten_01" },
			{ "46", "jinik_kaito_idosaki_01" },
			{ "47", "jinik_kaito_konin_youhi_01" },
			{ "48", "jinik_kaito_konin_youken_01" },
			{ "49", "jinik_kaito_ido_02" },
			{ "50", "jinik_kaito_taishoku_02" },
			{ "51", "jinik_kaito_tanto_gyomu_02" },
			{ "52", "jinik_kaito_ido_month_02" },
			{ "53", "jinik_kaito_shokumu_02" },
			{ "54", "jinik_kaito_jigyojo_02" },
			{ "55", "jinik_kaito_kyoten_02" },
			{ "56", "jinik_kaito_idosaki_kyoten_02" },
			{ "57", "jinik_kaito_idosaki_02" },
			{ "58", "jinik_kaito_konin_youhi_02" },
			{ "59", "jinik_kaito_konin_youken_02" },
			{ "60", "jinik_kaito_ido_03" },
			{ "61", "jinik_kaito_taishoku_03" },
			{ "62", "jinik_kaito_tanto_gyomu_03" },
			{ "63", "jinik_kaito_ido_month_03" },
			{ "64", "jinik_kaito_shokumu_03" },
			{ "65", "jinik_kaito_jigyojo_03" },
			{ "66", "jinik_kaito_kyoten_03" },
			{ "67", "jinik_kaito_idosaki_kyoten_03" },
			{ "68", "jinik_kaito_idosaki_03" },
			{ "69", "jinik_kaito_konin_youhi_03" },
			{ "70", "jinik_kaito_konin_youken_03" },
			{ "71", "jinik_kaito_ido_04" },
			{ "72", "jinik_kaito_taishoku_04" },
			{ "73", "jinik_kaito_tanto_gyomu_04" },
			{ "74", "jinik_kaito_ido_month_04" },
			{ "75", "jinik_kaito_shokumu_04" },
			{ "76", "jinik_kaito_jigyojo_04" },
			{ "77", "jinik_kaito_kyoten_04" },
			{ "78", "jinik_kaito_idosaki_kyoten_04" },
			{ "79", "jinik_kaito_idosaki_04" },
			{ "80", "jinik_kaito_konin_youhi_04" },
			{ "81", "jinik_kaito_konin_youken_04" },
			{ "82", "jinik_kaito_ido_05" },
			{ "83", "jinik_kaito_taishoku_05" },
			{ "84", "jinik_kaito_tanto_gyomu_05" },
			{ "85", "jinik_kaito_ido_month_05" },
			{ "86", "jinik_kaito_shokumu_05" },
			{ "87", "jinik_kaito_jigyojo_05" },
			{ "88", "jinik_kaito_kyoten_05" },
			{ "89", "jinik_kaito_idosaki_kyoten_05" },
			{ "90", "jinik_kaito_idosaki_05" },
			{ "91", "jinik_kaito_konin_youhi_05" },
			{ "92", "jinik_kaito_konin_youken_05" },
			{ "93", "jinik_kaito_ido_06" },
			{ "94", "jinik_kaito_tanto_gyomu_06" },
			{ "95", "jinik_kaito_shokumu_06" },
			{ "96", "jinik_kaito_jigyojo_06" },
			{ "97", "jinik_kaito_kyoten_06" },
			{ "98", "jinik_kaito_idosaki_kyoten_06" },
			{ "99", "jinik_kaito_idosaki_06" },
			{ "100", "jinik_kaito_konin_youhi_06" },
			{ "101", "jinik_kaito_konin_youken_06" },
			{ "102", "jinik_kaito_other" }
	};
}
