@echo off

SET DB_SYS_USER=SYSTEM
SET DB_SYS_PASSWORD=SYSTEM
SET DB_USER=CAREER
SET DB_PASSWORD=CAREER
SET ORACLE_SID=DAIKO
REM SET ORACLE_SID=CAREER
REM SET ORACLE_SID=127.0.0.1:1522/CAREER

exit /b
